'''
just a small example of exhaustive train on the core parameters of 
the prediction algorithm
'''

from train import train_model
from utils import create_folder
import tensorflow as tf
import os

tf.config.experimental_run_functions_eagerly(True)

if __name__ == '__main__':

    # create a base folder for all the checkpoints
    base_folder = 'checkpoints'
    create_folder(base_folder)

    # specify pca_components lengths
    spectral_dimensions = [16]

    # specify windows sizes
    spatial_dimensions = [15]

    # insert training sets path generated by euclidean interpollation
    datasets_path = 'customTrainingSet'
    datasets = os.listdir(datasets_path)


    for dataset in datasets:
        for spec_dim in spectral_dimensions:
            for spatial_dim in spatial_dimensions:
                save_folder = '{}/model_size_{}_spec_{}_thres_{}'.format(
                    base_folder, spatial_dim, spec_dim, dataset)

                curr_dataset = os.path.join(datasets_path, dataset)

                train_model(spec_dim,
                            spatial_dim,
                            dataset_folder=curr_dataset,
                            epochs=100,
                            save_folder=save_folder,
                            model_type='residual',
                            train_mode='euclidean')
